apiVersion: skaffold/v4beta5
kind: Config
# added for post deploy 3p example
customActions:
- name: postdeploy-action
  containers:
  - name: predeploy-echo
    image: gcr.io/gcp-runtimes/ubuntu_18_0_4
    command: ["curl"]
    args: ["https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=https://google.com"]
build:
  artifacts:
    - image: scdongcp-app
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - kubernetes/dev
profiles:
  - name: qa
    manifests:
      kustomize:
        paths:
          - kubernetes/qa
  - name: prod
    manifests:
      kustomize:
        paths:
          - kubernetes/prod