apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: scdongcp-app
build:
  artifacts:
    - image: ch6-scdongcp
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - kubernetes/deployment.yaml
